---
version: '3'

networks:
  wade-network:

services:
  database:
    build:
      context: ./database
    ports:
      - "5432:5432"
    networks:
      wade-network:
        aliases:
          - database
    env_file:
      - "compose${DOCKER_WADE_ENV_LOCAL}.env"
    container_name: wade_database

  web:
    build:
      context: ./web
    ports:
      - "80:80"
      - "443:443"
    networks:
      wade-network:
        aliases:
          - web
    env_file:
      - "compose${DOCKER_WADE_ENV_LOCAL}.env"
    container_name: wade_web
    volumes:
      - ~/Development/Source/CIDA/WADE_WMA_OVERLAY/webservices/WADE/v0.2/:/var/www/html/dev:ro
    depends_on:
      - database

  jenkins:
    build:
      context: ./jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    env_file:
      - "./jenkins/compose${DOCKER_JENKINS_ENV_LOCAL}.env"
