--Group Roles and Login Roles for WaDE PostgreSQL database restore
DO $$BEGIN
CREATE ROLE "WADE_ADMIN" WITH
	NOLOGIN
	SUPERUSER
	CREATEDB
	CREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1;
CREATE ROLE "WADE_APP" WITH
	NOLOGIN
	SUPERUSER
	CREATEDB
	CREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1;
END $$;
DO $$BEGIN
CREATE USER "WADE" WITH
	LOGIN
	SUPERUSER
	CREATEDB
	CREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1;
CREATE USER "wade_app1" WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	NOINHERIT
	NOREPLICATION
	CONNECTION LIMIT -1;

END $$;

DO $$BEGIN
GRANT "WADE_ADMIN" TO "WADE";
GRANT "WADE_APP" TO "wade_app1";
END $$;
